#robot:
dof: 6
dim_task: 3 #7
dim_pos: 3
robot_name: "gen3lite"
root_link: "kinova_base_link"
end_links: ["tool_frame"]
collision_links: ["upper_wrist_link", "end_effector_link"]
collision_radii: {5: 0.10, 6: 0.05}
vel_limits: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
iiwa_limits: [
    [-2.8973, 2.8973],
    [-1.7628, 1.7628],
    [-2.8973, 0.7],
    [-3.0718, -0.0698],
    [-2.8973, 2.8973],
    [-0.0175, 3.7525],
  ]
#default settings:
render: True
bool_energy_regulator: True
bool_speed_control: True
bool_extensive_concretize: True
mode: "vel"        # mode of fabrics (vel or acc)
mode_NN: "1st"
mode_env: "vel"
dt: 0.025
nr_obst: 2
positions_obstacles: [[0.5, -0.25, 0.5], [10.24355761, 10.45252747, 10.2]]
speed_obstacles: [[0., 0., 0.], [0., 0., 0.]]
nr_obst_dyn: 0
goal_reached_threshold: 0.02
n_steps: 2000
init_pos: [-0.702, 0.355, -0.016, -1.212, 0.012, -0.502, -0.010]
goal_pos: [0.58, -0.214,  0.115]
goal_vel: [0., 0., 0.]
orientation_goal: [ 0.02963833,  0.88385373, -0.01450962,  0.46659793]
params_name_1st: "1st_order_3D_kinova"
params_name_2nd: "2nd_order_R3S3_kinova"